services:
  - type: web
    name: portfolio-pwa
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: NODE_VERSION
        value: "20"
